# Generated by Django 4.2.19 on 2025-02-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
