# Generated by Django 3.1.12 on 2025-02-26 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20250225_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
