# Generated by Django 3.1.12 on 2025-02-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('packing', 'Packing'), ('shipping', 'Shipping'), ('delivered', 'Delivered')], default='packing', max_length=10),
        ),
    ]
