"""
Django settings for vhanh_project1 project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#p(o)6p7@o13*=e)g7q%oyt$@+zq=h662f8d+e-n_t9126qjmf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Thay đổi thời gian hết hạn
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# ZALOPAY = {
#     'APP_ID': '2554',
#     'KEY1': 'sdngKKJmqEMzvh5QQcdD2A9XBSKUNaYn',
#     'KEY2': 'trMrHtvjo6myautxDUiAcYsVtaeQ8nhf',
#     'CREATE_ORDER_URL': 'https://sandbox.zalopay.vn/v2/create',
#     'RETURN_URL': 'http://127.0.0.1:8000/payment/success/',
#     'CALLBACK_URL': 'http://127.0.0.1:8000/payment/callback/',
# }


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'customer',
    'book',
    'cart',
    'rest_framework',
    'rest_framework_simplejwt',
    'seller',
    'base',
    'clothes',
    'corsheaders',
    'django_filters',
    'product',
    'shoes',
    'electronics',
    'orders',
    'coupons',
    # 'payment',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

AUTH_USER_MODEL = 'base.BaseUser'
# AUTH_USER_MODEL = 'customer.Customer'


# Multi-authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',            # BaseUser (Admin/Staff) - SQLite
    'customer.backends.CustomerAuthBackend',                # Customer - MySQL
    'seller.backends.SellerAuthBackend',                # Seller - MySQL
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ALLOWED_HOSTS = ["127.0.0.1", "localhost" ]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # FE Vite/React
    "http://127.0.0.1:5173",
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'vhanh_project1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vhanh_project1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'cartdb': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'eCommerceDB',
        'USER': 'ecommerce_user',
        'PASSWORD': 'ecommerce_password',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    # MySQL cho Customer
    'mysql_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'eCommerceDB',
        'USER': 'ecommerce_user',
        'PASSWORD': 'ecommerce_password',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'ecommercedb': {
        'ENGINE': 'djongo',
        'NAME': 'ecommercedb',
        'CLIENT': {
            'host': 'mongodb+srv://tranducscc:j6jYAlDSsfZT398i@iot.7srk5.mongodb.net/ecommercedb',
            'username': 'tranducscc',
            'password': 'j6jYAlDSsfZT398i',
            'authSource': 'admin',
        }
    }
}

DATABASE_ROUTERS = ['vhanh_project1.db_router.ECommerceDBRouter']


# from mongoengine import connect

# connect(
#     db='itemdb',
#     host='mongodb+srv://anhvh243:Kv9RzWTuamVcTlif@cluster0.xgxi5.mongodb.net/itemdb',
#     username='anhvh243',
#     password='Kv9RzWTuamVcTlif',
#     authentication_source='admin'
# )


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
