# Generated by Django 3.1.12 on 2025-02-26 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('author', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
            ],
            bases=('product.product',),
        ),
    ]
