# Generated by Django 3.1.12 on 2025-02-26 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('product_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('brand', models.CharField(max_length=100)),
                ('warranty_period', models.CharField(max_length=50)),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('product_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('size', models.IntegerField()),
                ('material', models.CharField(max_length=100)),
            ],
            bases=('product.product',),
        ),
    ]
