# Generated by Django 3.1.12 on 2025-02-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_id',
        ),
    ]
